export const UPDATE_STEP = "UPDATE_STEP";
export const UPDATE_ACTIVE_STEP_ID = 'UPDATE_ACTIVE_STEP_ID';

export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const RESET_FORM = 'RESET_FORM';

export const UPDATE_FORM = "UPDATE_FORM";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const SUBMIT_APPLICATION = "SUBMIT_APPLICATION";
export const FILL_ANOTHER_RESPONSE = "FILL_ANOTHER_RESPONSE";